language: php
dist: jammy
php:
  - 8.1
  - 8.2
env: PHPV=0
install: |
  composer install
script: |
  composer run-script test -- --colors
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.titi
    - vendor
