language: php
php:
  - 8.1
env:
  - PHPV=0
  - XDEBUG_MODE=coverage
install: |
  composer install
script: |
  composer run-script test -- --colors --coverage-text
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.titi
    - vendor
